# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Set Recipe & Chef of the day

on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'

jobs:

  set-stuff-of-the-day:
    name: Hit API
    runs-on: ubuntu-latest

    steps:

      - name: Install JQ
        run: sudo apt-get install -y jq

      - name: Hit API Endpoint
        run: |
          curl -X POST -s -o '/tmp/output.txt' --url ${{ secrets.PROJECT_DOMAIN }}/api/v1/system/ops/set-recipe-chef-of-the-day.php
          #cat /tmp/output.txt
          MESSAGE=$(echo $(cat /tmp/output.txt) | jq -r '.message')
          CODE=$(echo $(cat /tmp/output.txt) | jq -r '.response_code')
          echo "Response: $MESSAGE"
          
          if [ $CODE != "200" ]; then
            echo "FAILURE";
            exit 1;
          else
            echo "SUCCESS";
          fi
